// -------------------------------------------------------------
// 
// File Name: hdl_prj\hdlsrc\hdlcoder_sincos_control\SinCos.v
// Created: 2024-10-17 22:45:02
// 
// Generated by MATLAB 9.14 and HDL Coder 4.1
// 
// 
// -- -------------------------------------------------------------
// -- Rate and Clocking Details
// -- -------------------------------------------------------------
// Model base rate: 1
// Target subsystem base rate: 1
// 
// 
// Clock Enable  Sample Time
// -- -------------------------------------------------------------
// ce_out        1
// -- -------------------------------------------------------------
// 
// 
// Output Signal                 Clock Enable  Sample Time
// -- -------------------------------------------------------------
// sineOut                       ce_out        1
// cosOut                        ce_out        1
// validOut                      ce_out        1
// -- -------------------------------------------------------------
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: SinCos
// Source Path: hdlcoder_sincos_control/SinCos
// Hierarchy Level: 0
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module SinCos
          (clk,
           reset,
           clk_enable,
           dataIn,
           validIn,
           ce_out,
           sineOut,
           cosOut,
           validOut);


  input   clk;
  input   reset;
  input   clk_enable;
  input   signed [15:0] dataIn;  // sfix16_En13
  input   validIn;
  output  ce_out;
  output  signed [15:0] sineOut;  // sfix16_En14
  output  signed [15:0] cosOut;  // sfix16_En14
  output  validOut;


  wire enb;
  reg  [0:11] hdl_Delay_reg;  // ufix1 [12]
  wire [0:11] hdl_Delay_reg_next;  // ufix1 [12]
  wire y;
  wire switch_compare_1;
  wire signed [15:0] y_1;  // sfix16_En14
  wire signed [15:0] y_2;  // sfix16_En14
  wire signed [15:0] Switch_out1;  // sfix16_En14
  reg signed [15:0] Delay_out1;  // sfix16_En14
  wire switch_compare_1_1;
  wire signed [15:0] Switch1_out1;  // sfix16_En14
  reg signed [15:0] Delay1_out1;  // sfix16_En14


  assign enb = clk_enable;

  always @(posedge clk)
    begin : hdl_Delay_process
      if (reset == 1'b1) begin
        hdl_Delay_reg[0] <= 1'b0;
        hdl_Delay_reg[1] <= 1'b0;
        hdl_Delay_reg[2] <= 1'b0;
        hdl_Delay_reg[3] <= 1'b0;
        hdl_Delay_reg[4] <= 1'b0;
        hdl_Delay_reg[5] <= 1'b0;
        hdl_Delay_reg[6] <= 1'b0;
        hdl_Delay_reg[7] <= 1'b0;
        hdl_Delay_reg[8] <= 1'b0;
        hdl_Delay_reg[9] <= 1'b0;
        hdl_Delay_reg[10] <= 1'b0;
        hdl_Delay_reg[11] <= 1'b0;
      end
      else begin
        if (enb) begin
          hdl_Delay_reg[0] <= hdl_Delay_reg_next[0];
          hdl_Delay_reg[1] <= hdl_Delay_reg_next[1];
          hdl_Delay_reg[2] <= hdl_Delay_reg_next[2];
          hdl_Delay_reg[3] <= hdl_Delay_reg_next[3];
          hdl_Delay_reg[4] <= hdl_Delay_reg_next[4];
          hdl_Delay_reg[5] <= hdl_Delay_reg_next[5];
          hdl_Delay_reg[6] <= hdl_Delay_reg_next[6];
          hdl_Delay_reg[7] <= hdl_Delay_reg_next[7];
          hdl_Delay_reg[8] <= hdl_Delay_reg_next[8];
          hdl_Delay_reg[9] <= hdl_Delay_reg_next[9];
          hdl_Delay_reg[10] <= hdl_Delay_reg_next[10];
          hdl_Delay_reg[11] <= hdl_Delay_reg_next[11];
        end
      end
    end

  assign y = hdl_Delay_reg[11];
  assign hdl_Delay_reg_next[0] = validIn;
  assign hdl_Delay_reg_next[1] = hdl_Delay_reg[0];
  assign hdl_Delay_reg_next[2] = hdl_Delay_reg[1];
  assign hdl_Delay_reg_next[3] = hdl_Delay_reg[2];
  assign hdl_Delay_reg_next[4] = hdl_Delay_reg[3];
  assign hdl_Delay_reg_next[5] = hdl_Delay_reg[4];
  assign hdl_Delay_reg_next[6] = hdl_Delay_reg[5];
  assign hdl_Delay_reg_next[7] = hdl_Delay_reg[6];
  assign hdl_Delay_reg_next[8] = hdl_Delay_reg[7];
  assign hdl_Delay_reg_next[9] = hdl_Delay_reg[8];
  assign hdl_Delay_reg_next[10] = hdl_Delay_reg[9];
  assign hdl_Delay_reg_next[11] = hdl_Delay_reg[10];



  assign switch_compare_1 = y > 1'b0;



  SinCos_cordic_nw u_SinCos (.clk(clk),
                             .reset(reset),
                             .enb(clk_enable),
                             .angle(dataIn),  // sfix16_En13
                             .sin(y_1),  // sfix16_En14
                             .cos(y_2)  // sfix16_En14
                             );

  always @(posedge clk)
    begin : Delay_process
      if (reset == 1'b1) begin
        Delay_out1 <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          Delay_out1 <= Switch_out1;
        end
      end
    end



  assign Switch_out1 = (switch_compare_1 == 1'b0 ? Delay_out1 :
              y_1);



  assign sineOut = Switch_out1;

  assign switch_compare_1_1 = y > 1'b0;



  always @(posedge clk)
    begin : Delay1_process
      if (reset == 1'b1) begin
        Delay1_out1 <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          Delay1_out1 <= Switch1_out1;
        end
      end
    end



  assign Switch1_out1 = (switch_compare_1_1 == 1'b0 ? Delay1_out1 :
              y_2);



  assign cosOut = Switch1_out1;

  assign validOut = y;

  assign ce_out = clk_enable;

endmodule  // SinCos

