-d C:\repositories\noise_cancelling\noise_cancelling\impl\gwsynthesis\noise_cancelling.vg
-p GW2A-18C-PBGA256-8
-pn GW2A-LV18PG256C8/I7
-cst C:\repositories\noise_cancelling\noise_cancelling\src\noise_cancelling.cst
-cfg C:\repositories\noise_cancelling\noise_cancelling\impl\pnr\device.cfg
-bit
-tr
-ph
-timing
-cst_error
-correct_hold 1
-route_maxfan 23
-global_freq 100.000
